sudo: required

language: generic

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y gnupg curl libgetopt-long-descriptive-perl wget python-pygments fontconfig"

before_script:
  # Download Textlive 2018 Installer
  - curl -sL http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz | tar zxf -
  - mv install-tl-2018* install-tl
  - cd install-tl
  - echo "selected_scheme scheme-small" > profile
  - sudo ./install-tl -profile profile
  - cd ..
  - rm -rf install-tl
  # Update PATH
  - export PATH="/usr/local/texlive/2018/bin/x86_64-linux:$PATH"
  # Check texlive version
  - tlmgr version -v
  # Initialize some data structure required for tlmgr
  - tlmgr init-usertree
  - sudo $(which tlmgr) install enumitem
  - sudo $(which tlmgr) install geometry
  - sudo $(which tlmgr) install hyperref
  - sudo $(which tlmgr) install listings
  - sudo $(which tlmgr) install mathtools
  - sudo $(which tlmgr) install physics
  - sudo $(which tlmgr) install cancel
  # Check which tex packages we have available
  - tlmgr info --only-installed ||
        echo "Couldn't retrieve the texlive package list\!"
script:
  - pdflatex -halt-on-error -interaction nonstopmode document.tex
  # IF REFERENCES ARE PRESENT
  # - pdflatex -halt-on-error -interaction nonstopmode document.tex &&
  #   bibtex document.tex &&
  #   pdflatex -halt-on-error -interaction nonstopmode document.tex &&
  #   pdflatex -halt-on-error -interaction nonstopmode document.tex

