sudo: required

language: generic

before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"

before_script:
  # Check texlive version
  - tlmgr version -v
  # Check which tex packages we have available
  - tlmgr info --only-installed ||
        echo "Couldn't retrieve the texlive package list!"

###############################################################################
script:
  - pdflatex -halt-on-error -interaction nonstopmode document.tex &&
    bibtex document.tex &&
    pdflatex -halt-on-error -interaction nonstopmode document.tex &&
    pdflatex -halt-on-error -interaction nonstopmode document.tex
