sudo: required

language: generic

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

addons:
  apt:
    update: true
    packages:
      - gnupg
      - curl
      - libgetopt-long-descriptive-perl
      - wget
      - python-pygments
      - fontconfig

before_script:
  # Export PATH
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
  # Download Textlive 2018 Installer
  - ./texlive/install_texlive.sh
  # Install required packages
  - tlmgr install l3packages
  - tlmgr install l3kernel
  - tlmgr install enumitem
  - tlmgr install geometry
  - tlmgr install hyperref
  - tlmgr install listings
  - tlmgr install mathtools
  - tlmgr install physics
  - tlmgr install cancel

script:
  - pdflatex -halt-on-error -interaction nonstopmode document.tex
  # IF REFERENCES ARE PRESENT
  # - pdflatex -halt-on-error -interaction nonstopmode document.tex &&
  #   bibtex document.tex &&
  #   pdflatex -halt-on-error -interaction nonstopmode document.tex &&
  #   pdflatex -halt-on-error -interaction nonstopmode document.tex

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "frazar0"
  - git config --local user.email "frazar0@hotmail.it"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "document.pdf"
  skip_cleanup: true
